FROM docker.io/jenkins/jenkins:lts-alpine

USER root

RUN apk add --no-cache rsync tzdata make

RUN curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip \
    && unzip rclone-current-linux-amd64.zip \
    && cp rclone-*-linux-amd64/rclone /usr/local/bin \
    && chmod 755 /usr/local/bin/rclone \
    && rm -rf rclone-*

USER jenkins
